#!/bin/bash

if ! [ -t 0 ]; then
	read -a ref
fi


IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ $branch == "master" ]; then
	crumb=$(curl -u "ebzdag:Eb1123b*" -s 'http://159.203.43.213:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
	curl -u "ebzdag:Eb1123b*" -H "$crumb" -X POST http://159.203.43.213:8080/job/auto_seed_project/build?delay=0sec

	if [ $? -eq 0 ]; then
		echo "*** Ok"
	else
		echo "*** Error"
	fi

fi

