version: '3'
services:
  jenkins:
    container_name: jenkins
    image: docker-jenkins
    build:
      context: .
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
networks:
  jenkins: